Create normal user
valoup917/user_management pull request #36
Opened 2024-05-08 10:22 UTC by AntoineVRG

Ajout d'un bouton de vibration

2024-05-09 05:43 UTC, valoup917 requested changes

2024-05-09 05:43 UTC, valoup917 commented on lib/components/vibration_service.dart
> +      // Si le téléhpone n'a pas de vibration
ahah du coup tu peux enlever le else si ta rien dedans

2024-05-09 05:43 UTC, valoup917 commented on lib/pages/home.dart
> +// ignore_for_file: use_named_constants
a mon avis t'es pas obligé de mettre ca, pourquoi tu l'as mis ?

2024-05-10 20:26 UTC, AntoineVRG commented on lib/pages/home.dart
> +// ignore_for_file: use_named_constants
Je l'avais mis parce que j'ai des exentions sur vscode qui m'indiquaient ça et ça me perturbé

2024-05-11 08:35 UTC, merged